// Generated by scripts/generate-env.js
// En producción (Vercel), este archivo es sobreescrito por el buildCommand con las variables reales.
// En desarrollo local, edita los valores aquí directamente (NO commitear claves reales).
window.__env = {
  "SUPABASE_URL": "https://amfxytanmtvhferigddf.supabase.co",
  "SUPABASE_KEY": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtZnh5dGFubXR2aGZlcmlnZGRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxNzUxNDEsImV4cCI6MjA4ODc1MTE0MX0.f_JyiyGJ2uNPBF-UOffBYDQKPHRvlPVh89Mfo1qibmo",
  "SUPER_ADMIN_EMAIL": "",
  "DEV_MODE": false
};
