// Generated by scripts/generate-env.js
// En producción (Vercel), este archivo es sobreescrito por el buildCommand con las variables reales.
// En desarrollo local, edita los valores aquí directamente (NO commitear claves reales).
window.__env = {
  "SUPABASE_URL": "",
  "SUPABASE_KEY": "",
  "SUPER_ADMIN_EMAIL": "",
  "DEV_MODE": false
};
