const fs = require('fs');
const path = require('path');

const outPath = path.join(__dirname, '..', 'js', 'env.js');

const env = {
  SUPABASE_URL: process.env.SUPABASE_URL || '',
  SUPABASE_KEY: process.env.SUPABASE_KEY || '',
  SUPER_ADMIN_EMAIL: process.env.SUPER_ADMIN_EMAIL || '',
  DEV_MODE: process.env.DEV_MODE === 'true' || false
};

const content = `// Generated by scripts/generate-env.js
window.__env = ${JSON.stringify(env, null, 2)};
`;

fs.writeFileSync(outPath, content, 'utf8');
console.log('Wrote', outPath);
