const fs = require('fs');
const path = require('path');

/**
 * scripts/generate-env.js
 * Genera el archivo js/env.js dinámicamente en Vercel durante el Build Step.
 * Esto permite usar variables de entorno del sistema (process.env) en JS de cliente.
 */

const envContent = `/**
 * Generated by scripts/generate-env.js
 * Este archivo es sobreescrito por Vercel durante el build.
 */
window.__env = {
  SUPABASE_URL: "${process.env.SUPABASE_URL || ''}",
  SUPABASE_KEY: "${process.env.SUPABASE_KEY || ''}",
  SUPER_ADMIN_EMAIL: "${process.env.SUPER_ADMIN_EMAIL || ''}",
  DEV_MODE: ${process.env.DEV_MODE === 'true'}
};
`;

const outputPath = path.join(__dirname, '../js/env.js');

try {
  fs.writeFileSync(outputPath, envContent);
  console.log('[ClickSaaS] ✓ Archivo js/env.js generado con éxito.');
} catch (err) {
  console.error('[ClickSaaS] ❌ Error generando js/env.js:', err);
  process.exit(1);
}
